# Generated by Django 3.2.7 on 2021-09-06 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('useremail', models.EmailField(max_length=254)),
                ('userpassword', models.CharField(max_length=200)),
                ('userimage', models.ImageField(blank=True, default='/user-profiles/default.png', upload_to='user-profiles')),
                ('usermobilenumber', models.CharField(blank=True, max_length=200)),
                ('userdob', models.DateField(default='2021-12-19')),
            ],
        ),
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_name', models.CharField(max_length=200)),
                ('task_details', models.TextField()),
                ('task_created_date', models.DateField(auto_now_add=True)),
                ('test_created_time', models.TimeField(auto_now_add=True)),
                ('task_end_date', models.DateField()),
                ('task_end_time', models.TimeField()),
                ('task_status', models.CharField(default=False, max_length=200)),
                ('task_due_date_color_data', models.CharField(default='black', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userregister')),
            ],
        ),
    ]
