# Generated by Django 3.2.7 on 2021-09-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdata',
            name='task_due_date_color_data',
        ),
    ]
