# Generated by Django 3.2.7 on 2021-09-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_taskdata_task_due_date_color_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskData',
        ),
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
