# Generated by Django 3.2.7 on 2021-09-06 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20210906_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_details', models.TextField()),
                ('task_created_date', models.DateField(auto_now_add=True)),
                ('test_created_time', models.TimeField(auto_now_add=True)),
                ('task_end_date', models.DateField()),
                ('task_end_time', models.TimeField()),
                ('task_status', models.CharField(default=False, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
